function write_calibration_header(calibration, outputPath)
%WRITE_CALIBRATION_HEADER Export the fitted amplitude lookup as C constants.

[fileId, message] = fopen(outputPath, 'w');
if fileId < 0
    error('Calibration:HeaderWrite', ...
        'Cannot create %s: %s', outputPath, message);
end
cleanup = onCleanup(@() fclose(fileId)); %#ok<NASGU>

fprintf(fileId, '#ifndef TASK0729_AUTO_CALIBRATION_DATA_H\n');
fprintf(fileId, '#define TASK0729_AUTO_CALIBRATION_DATA_H\n\n');
fprintf(fileId, '/* Generated by MATLAB UTG2062X auto calibration. */\n');
fprintf(fileId, '#define TASK0729_AUTO_CALIBRATION_VALID 1U\n');
fprintf(fileId, '#define TASK0729_AUTO_CALIBRATION_KNOT_COUNT %dU\n', ...
    numel(calibration.KnotMeasuredVpk_mV));
fprintf(fileId, '#define TASK0729_AUTO_CALIBRATION_GAIN_ONLY %.9gF\n', ...
    calibration.GainOnly);
fprintf(fileId, '#define TASK0729_AUTO_RECOMMENDED_FRONTEND_GAIN %.9gF\n\n', ...
    calibration.RecommendedFrontendGain);

writeArray(fileId, 'task0729_auto_measured_vpk_v', ...
    calibration.KnotMeasuredVpk_mV / 1000);
fprintf(fileId, '\n');
writeArray(fileId, 'task0729_auto_target_vpk_v', ...
    calibration.KnotTargetVpk_mV / 1000);
fprintf(fileId, '\n#endif /* TASK0729_AUTO_CALIBRATION_DATA_H */\n');
end

function writeArray(fileId, name, values)
fprintf(fileId, 'static const float %s[%d] =\n{\n', ...
    name, numel(values));
for k = 1:numel(values)
    suffix = ',';
    if k == numel(values)
        suffix = '';
    end
    fprintf(fileId, '  %.9gF%s\n', values(k), suffix);
end
fprintf(fileId, '};\n');
end

